name: moneytracker_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  http: ^0.13.5
  intl: ^0.17.0
  provider: ^6.0.4
  page_transition: ^2.0.9
  jiffy: ^5.0.0
  syncfusion_flutter_charts: ^20.3.52

dev_dependencies:

  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/config/config.json
